language: java
sudo: false
install: true
jdk:
- oraclejdk8
os:
- linux
script:
- mvn clean test -Dgpg.skip
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=guckesrohrkagbr-github
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

