language: java
jdk:
  - oraclejdk8
  - oraclejdk9
os:
  - linux
  - osx
script:
  - mvn test -Dgpg.skip
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
addons:
  sonarqube:
    organization: "guckesrohrkagbr-github"
    token:
      secure: "pbQc0Yxlt2P696tztRD1Qys/uPd4piyM5bLipMLLK9olgW0U0Q/jGTAME/4JKZNq99DrOLqGPYcjzcv0NlzqGSK9Vu/jzUL96vOORNCeUMEPHIqNGm7JkfoQ7xCkszMavuMXM5mmrNWC7QQ8TOrfjcIdy7TA3cnNSi3KRVQVndT4GYH1bwzD8z0rjkyiN71SPw0ziPBHjEM1qcIKilNc++ggGAcIV3ObaYCwHPJyo9k2dDV2go0euCqtX1RMuIohU/69vg/l6pHdzx/GchTQajZJqDJFQ3RQGDu7O0HEGjttK5ncPoOCaWexbL8KsGaDCw8+4PtTanO2ZQXMQdmcys9iaxTU4fivSpEOIAsYTiq/7GPcKIFQ6PZiQxgxVBsHI2BC4hhbnAhjxuKvZVwFmp6ppfjtjthLbc4ZwfcnhwOo3NFy7ByUxkK2fUbhr3NfDHcYGsnZglB1oGyNuHX/+HM+2iTJh1UbfGI8bYmgREhD9auAYUdafgwVcKjOm4xi0nfIHr/gvMP0kiRfs1UPOzUHraZOdP4F9nX4ELwAy9+8RwrGs8o3lbSuXf51Z1g5Oe+gnnimJcpv36z1WuJVCfv+Y6hhddF+J6fyU/YeIkVvwPD+c2LpMG/h9QfGI26zSxgYjiEv8bW5EVIUPs2LiRnmiWgq3p+VX0HROC+kaTM="
