language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: guckesrohrkagbr-github
    token:
      secure: A2c1sYCtEFKsNZwvE1xExVvulJh2HaaZhisqQGtrVoIkG+ey4/aA8ib+9DwzeiyCYOXaugyhSazOA6K7V+491kXyHzG0im95qloWvs+gHPISu4B235ZzhOfj98AXcjFkOz1bWICOJzUiUoQmAi0VwIXh3z530TlUVmn6QFTJLYh9qtbIzgg+1PUqAUlo+23mHlKU5l4/MGhBZbMO5oAZ7/yAqqp6tvUTrlvsp9yEghTweysgs9ZE3w5cpLD2I7GezYTIJtxcXQ6gV/WhnxOQy2tRQ/HvgRvOQBpVH1YTat6gvqSxA8C3oS87513sDjmkK9EyiYtAgX9buBLzaaIXYeszHapwnF4oJvhMULNwpJpnhxnY9AUmlBIpgqkrGmkH2ix7AKU6se19L3uo40rq2umPwlYq3o9pnXDgHOXHCKF7ZM4zn4nLV+Qt8SQAYI3vTmi/iOC7QHiNJZVVR8WhfK/Ns6lczaTSk9DyGiEMYbNTJiT2etXPngh0r/DkxAzpCo4NJqRjhE1QeuDWGb0mkGvIqsyDLmTza5ofrwvQjUKfVBVyGXWGbb6wEaUVgMOq5tzTrboS4dhtnMUuMFpCNc18IaMp1saFtwoewyvzKcBPmBND+qtKUwNhi/gxvHeoG7IvwZfF0uiK2j6rdjA6EU/E+5CHfU59vY/M5Q3vJoc=
jdk:
- oraclejdk8
- oraclejdk9
os:
- linux
- osx
script:
- mvn test -Dgpg.skip
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

